### ISSUE TITLE
[FEAT] Add Code Scan Workflow

### ISSUE THREAD

**Issue by alphaX86** [nhcarrigan/we-love-matt#16]
# Feature Request

## Is your feature request related to a problem? Please describe:
No. It's just a suggestion

## Describe the solution you'd like
A code scanning workflow can be setup for TS code to scan vulnerabilities

**Comment by nhcarrigan** [comment]
I have an existing workflow that could be carried over from my other bot - it scans the built `.js` files. 

Otherwise, if there is a better option I'm definitely open to suggestions, but *I prefer to keep things through GitHub Actions*.

**Comment by alphaX86** [comment]
But I think you can add one directly from **GitHub Actions**

Example: CodeQL, Codacy

**Comment by nhcarrigan** [comment]
CodeQL is the workflow I have on the other bot. I can bring that over 😁
