### ISSUE TITLE
Add support for more people

### ISSUE THREAD

**Issue by Atharv-Attri** [nhcarrigan/we-love-matt#18]
# Feature Request

## Is your feature request related to a problem? Please describe:
Hacktoberfest is not held up entirely by just Matt. There are a lot of other amazing people like Raven and Luke who help make hacktoberfest rock!

## Describe the solution you'd like

I would like to add in support to appreciate more people. Whenever someone will mention someone else, It would return the saying with their name.

I would like to implement this myself. Can you please assign it to me?

**Comment by Atharv-Attri** [comment]
Alright, Let's talk to Matt and make sure everyone gets the appreciation that they deserve!

**Comment by Atharv-Attri** [comment]
Matt gave the go ahead! Can you assign it to me?

**Comment by nhcarrigan** [comment]
Alright, this is assigned to you. 

Let's use the `phrases.ts` file to hold the arrays and export them to the main file.

**Comment by Atharv-Attri** [comment]
Alright!
